USE [master]
GO
CREATE DATABASE [AdventureWorks2017]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AdventureWorks2017', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\AdventureWorks2017.mdf' , SIZE = 270336KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'AdventureWorks2017_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\AdventureWorks2017_log.ldf' , SIZE = 73728KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [AdventureWorks2017] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AdventureWorks2017].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [AdventureWorks2017] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [AdventureWorks2017] SET ANSI_NULLS ON 
GO
ALTER DATABASE [AdventureWorks2017] SET ANSI_PADDING ON 
GO
ALTER DATABASE [AdventureWorks2017] SET ANSI_WARNINGS ON 
GO
ALTER DATABASE [AdventureWorks2017] SET ARITHABORT ON 
GO
ALTER DATABASE [AdventureWorks2017] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [AdventureWorks2017] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [AdventureWorks2017] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [AdventureWorks2017] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [AdventureWorks2017] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [AdventureWorks2017] SET CONCAT_NULL_YIELDS_NULL ON 
GO
ALTER DATABASE [AdventureWorks2017] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [AdventureWorks2017] SET QUOTED_IDENTIFIER ON 
GO
ALTER DATABASE [AdventureWorks2017] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [AdventureWorks2017] SET  DISABLE_BROKER 
GO
ALTER DATABASE [AdventureWorks2017] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [AdventureWorks2017] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [AdventureWorks2017] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [AdventureWorks2017] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [AdventureWorks2017] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [AdventureWorks2017] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [AdventureWorks2017] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [AdventureWorks2017] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [AdventureWorks2017] SET  MULTI_USER 
GO
ALTER DATABASE [AdventureWorks2017] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [AdventureWorks2017] SET DB_CHAINING OFF 
GO
ALTER DATABASE [AdventureWorks2017] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [AdventureWorks2017] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [AdventureWorks2017] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'AdventureWorks2017', N'ON'
GO
ALTER DATABASE [AdventureWorks2017] SET QUERY_STORE = OFF
GO
USE [master]
GO
ALTER DATABASE [AdventureWorks2017] SET  READ_WRITE 
GO
USE [AdventureWorks2017]
GO
CREATE SCHEMA [HumanResources]
GO
CREATE SCHEMA [Person]
GO
CREATE SCHEMA [Production]
GO
CREATE SCHEMA [Purchasing]
GO
CREATE SCHEMA [Sales]
GO
